javac clientcommandhandler/ClientCommandHandler.java
javac clientconnection/ClientConnection.java
javac server/Server.java
javac servertest/ServerTest.java
javac usercommandhandler/UserCommandHandler.java
javac userinterface/StandardIO.java
